name: CI-R-TYPE
on:
    workflow_dispatch:
    push:

jobs:
    Compile_Unix:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: oprypin/install-sfml@v1
        - uses: egor-tensin/build-boost@v1
          with:
            version: 2.5.1
        - name: install dependencies and compile
          run: |
            sudo pip3 install -r requirements.txt
            sudo apt-get install libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev
            sudo python3 build.py

    Compile_Windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3
        - uses: microsoft/setup-msbuild@v1.1.3
        - uses: oprypin/install-sfml@v1
        - uses: egor-tensin/build-boost@v1
        - name: install tools
          run: |
            choco install python3
            choco install cmake
            choco install microsoft-build-tools
            choco install visualstudio2019buildtools
            choco install visualstudio2019-workload-vctools
            choco install visualstudio2019-workload-nativedesktop
            choco install visualstudio2019-workload-nativedesktopcore
            git clone https://github.com/Microsoft/vcpkg.git && .\vcpkg\bootstrap-vcpkg.bat
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: install dependencies and compile
          run: |
            pip install -r requirements.txt
            python3 build.py
